name: Notify for slack

inputs:
  SLACK_WEBHOOK_URL:
    description: Slack webhook url
  PULL_REQUEST_URL:
    description: プルリクのURL
  PULL_REQUEST_TITLE:
    description: プルリクのタイトル
  PULL_REQUEST_NUMBER:
    description: プルリクのナンバー

runs:
  using: 'composite'
  steps:
    - name: Notify success CI
      if: success()
      uses: slackapi/slack-github-action@v1.21.0
      with:
        payload: |
          {
            "attachments": [
              {
                "color": "good",
                "title": "${{ inputs.PULL_REQUEST_TITLE }} #${{ inputs.PULL_REQUEST_NUMBER }}",
                "text": "CI Result Success :white_check_mark: \nPR: ${{ inputs.PULL_REQUEST_URL }}"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
    - name: Notify failuer CI
      if: failure()
      uses: slackapi/slack-github-action@v1.21.0
      with:
        payload: |
          {
            "attachments": [
              {
                "color": "danger",
                "title": "${{ inputs.PULL_REQUEST_TITLE }} #${{ inputs.PULL_REQUEST_NUMBER }}",
                "text": "CI Failuer :x: \nPR: ${{ inputs.PULL_REQUEST_URL }} \nhead commit: ${{ github.event.head_commit.url }}"
              }
            ]
          }
      env:
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        SLACK_WEBHOOK_URL: ${{ inputs.SLACK_WEBHOOK_URL }}
