FROM golang:1.18.4-alpine AS builder
WORKDIR /go/src/app

RUN apk update && apk --no-cache add git
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build server.go

FROM alpine:latest
WORKDIR /root

COPY --from=builder /go/src/app/ /root

EXPOSE 80
CMD ["/root/server"]