version: '3'
services:
  graphql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app:cached
    command: air -c .air.toml
    environment:
      GO_MODE: development
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_NAME: changeable
      SECRET_HASH_KEY: YWJTIzPep2kKiYoKScdsa2tPUB31
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  db:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
