name: ci

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  go_test:
    name: Backend Api Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          go mod download
      - name: Run test
        run: |
          go test ./test/* -test.v
  go_fmt:
    name: Go format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.4'
      - uses: actions/cache@v2
        id: cache-go
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: |
          go mod download
      - uses: technote-space/get-diff-action@v6
        id: check-diff
        with:
          PATTERNS: |
            **/*
            !front/**/*
      - name: Run gofmt
        run: gofmt -l -s -w .
        if: steps.check-diff.outputs.diff