name: ci

on:
  push:
    branches-ignore:
      - main
  workflow_call:

jobs:
  go-fmt:
    name: Go format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run gofmt
        run: gofmt -l -s -w .
        id: fmt-diff

      - name: Check failure
        run: exit 1
        if: steps.fmt-diff.outputs.diff

  test:
    uses: ./.github/workflows/test.yml