name: ci

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  go_test:
    name: Backend Api Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./github/actions/setup-go
      - name: Run test
        run: |
          go test ./test/* -test.v
  go_fmt:  
    name: Go format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: technote-space/get-diff-action@v6
        id: check-diff
        with:
          PATTERNS: |
            **/*
            !front/**/*
      - uses: ./github/actions/setup-go
        if: steps.check-diff.outputs.diff
      - name: Run gofmt
        run: gofmt -l -s -w .
        if: steps.check-diff.outputs.diff
      - name: Check failure
        run: exit 1
        if: steps.check-diff.outputs.diff